### PR TITLE
Added couscous

### LINKED ISSUE #1: Free couscous?
Where is it?

### PR DESCRIPTION
**Pull request by sondregj**
Closes #1 and #2.

### CODE REVIEW

**Comment by arnemolland** [comment]
+1

**Comment by ghost** [comment]
+2

**Review by arnemolland — APPROVED** [review]

**Review by arnemolland — APPROVED** [review]
LGTM

**Comment by sondregj** [comment]
@andersfgraneng

**Review by andersfgraneng — APPROVED** [review]
Nice couscous

**Pull request merged**
