### PR TITLE
Create package manifest to receive free couscous

### LINKED ISSUE #2: Where is the couscous?

### PR DESCRIPTION
**Pull request by arnemolland**
Written in JOML format [Joe's Obvious Minimal Language]

You can read more about it here: https://www.github.com/arnemolland/joml

Fixes #2

### CODE REVIEW

**Review by sondregj — APPROVED** [review]

**Comment by ghost** [comment]
### +1

**Comment by sondregj** [comment]
+1

**Review by ghost — APPROVED** [review]
🥴

**Review by sondregj — CHANGES_REQUESTED** [review]
Maybe we should extend support for BOML as well?

**Comment by arnemolland** [comment]
> Maybe we should extend support for BOML as well?

Yes. @andersfgraneng will you take ownership of this issue?

**Review by sondregj — APPROVED** [review]

**Comment by arnemolland** [comment]
Bump

**Comment by sondregj** [comment]
This is way overdue.

**Pull request merged**
